In [0]:
from sklearn.preprocessing import MinMaxScaler

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
url = 'https://raw.githubusercontent.com/shanksghub/Musk.csv/master/musk_csv.csv'
df = pd.read_csv(url)
# Dataset is now stored in a Pandas Dataframe

In [168]:
df.head()

ID molecule_name conformation_name  f1   f2  ...  f163  f164  f165  f166  class
0   1      MUSK-211           211_1+1  46 -108  ...   156   -50  -112    96      1
1   2      MUSK-211          211_1+10  41 -188  ...   169   -61  -136    79      1
2   3      MUSK-211          211_1+11  46 -194  ...   165   -67  -145    39      1
3   4      MUSK-211          211_1+12  41 -188  ...   168   -60  -135    80      1
4   5      MUSK-211          211_1+13  41 -188  ...   168   -60  -135    80      1

[5 rows x 170 columns]

In [0]:
y = df[['class',]] 


In [170]:
y_array = df[['class']].to_numpy() 
print (y_array)

[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


In [171]:
y_array.ravel()

array([1, 1, 1, ..., 0, 0, 0])

In [172]:
df.drop(['class','ID','molecule_name','conformation_name'], axis = 1) 


f1   f2   f3   f4   f5   f6  ...  f161  f162  f163  f164  f165  f166
0     46 -108  -60  -69 -117   49  ...    39   126   156   -50  -112    96
1     41 -188 -145   22 -117   -6  ...   103   136   169   -61  -136    79
2     46 -194 -145   28 -117   73  ...   143   142   165   -67  -145    39
3     41 -188 -145   22 -117   -7  ...   104   136   168   -60  -135    80
4     41 -188 -145   22 -117   -7  ...   104   137   168   -60  -135    80
...   ..  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...
6593  51 -123  -23 -108 -117  134  ...   -29   107   171   -44  -115   118
6594  44 -104  -19 -105 -117  142  ...   150   129   158   -66  -144    -5
6595  44 -102  -19 -104 -117   72  ...   150   130   159   -66  -144    -6
6596  51 -121  -23 -106 -117   63  ...   -31   106   171   -44  -116   117
6597  51 -122  -23 -106 -117  190  ...   -30   107   171   -44  -115   118

[6598 rows x 166 columns]

In [0]:
X = df.drop(['class','ID','molecule_name','conformation_name'], axis = 1) 


In [0]:
scaler = MinMaxScaler(feature_range=(0, 1))
X = scaler.fit_transform(X)

In [175]:
X

array([[0.23839009, 0.30952381, 0.43145161, ..., 0.40924658, 0.53020134,
        0.67661098],
       [0.22291022, 0.03741497, 0.08870968, ..., 0.39041096, 0.48993289,
        0.65632458],
       [0.23839009, 0.0170068 , 0.08870968, ..., 0.38013699, 0.47483221,
        0.60859189],
       ...,
       [0.23219814, 0.32993197, 0.59677419, ..., 0.38184932, 0.47651007,
        0.5548926 ],
       [0.25386997, 0.26530612, 0.58064516, ..., 0.41952055, 0.52348993,
        0.70167064],
       [0.25386997, 0.26190476, 0.58064516, ..., 0.41952055, 0.52516779,
        0.70286396]])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
from sklearn.linear_model import LogisticRegression


In [177]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
predictions = logmodel.predict(X_test)


In [0]:
from sklearn.metrics import classification_report


In [180]:
print(classification_report(y_test,predictions))


              precision    recall  f1-score   support

           0       0.94      0.98      0.96      1111
           1       0.87      0.67      0.76       209

    accuracy                           0.93      1320
   macro avg       0.90      0.83      0.86      1320
weighted avg       0.93      0.93      0.93      1320

